/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import DTO.LicenciaDTO;
import DTO.PersonaDTO;
import DTO.PlacaDTO;
import DTO.VehiculoDTO;
import EntidadesJPA.EntidadPersona;
import EntidadesJPA.EntidadVehiculo;
import Negocio.CrearPlaca;
import Negocio.ObtenerLicencia;
import Negocio.ObtenerPersona;
import Negocio.ObtenerVehiculo;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class frmGenerarPlacas extends javax.swing.JFrame {
    EntidadPersona p;

    /**
     * Creates new form frmGenerarPlacas
     */
    public frmGenerarPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRFCAuto = new javax.swing.JTextField();
        btnContinuarAutoNuevo = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtSeriePlaca = new javax.swing.JTextField();
        btnAtrasGenerarPlacas = new javax.swing.JButton();
        comboBoxVehiculos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(0, 51, 102));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("LICENCIA VIGENTE");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("RFC");

        btnContinuarAutoNuevo.setBackground(new java.awt.Color(0, 102, 102));
        btnContinuarAutoNuevo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnContinuarAutoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarAutoNuevo.setText("Continuar");
        btnContinuarAutoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarAutoNuevoActionPerformed(evt);
            }
        });

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRFCAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuarAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRFCAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(btnContinuarAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 300, 430));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Generar placas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 310, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serie placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 370, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehiculo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtSeriePlaca.setEditable(false);
        txtSeriePlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeriePlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeriePlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, -1));

        btnAtrasGenerarPlacas.setBackground(new java.awt.Color(0, 102, 102));
        btnAtrasGenerarPlacas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAtrasGenerarPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasGenerarPlacas.setText("Atras");
        btnAtrasGenerarPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasGenerarPlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtrasGenerarPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 190, 50));

        comboBoxVehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camion", "Moto" }));
        comboBoxVehiculos.setEnabled(false);
        comboBoxVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxVehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarAutoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarAutoNuevoActionPerformed
       // Se divide la cadena seleccionada en el comboBoxVehiculos en partes utilizando el espacio como delimitador
        String[] partes = comboBoxVehiculos.getSelectedItem().toString().split(" ");

        // Se obtiene la serie del vehículo, que es la parte antes del primer espacio
        String serie = partes[0];

        // Se crea un objeto VehiculoDTO con la serie del vehículo y la información de la persona
        ObtenerVehiculo ov = new ObtenerVehiculo();
        VehiculoDTO vehiDTO = new VehiculoDTO(serie, this.p);

        try {
            // Se intenta obtener el vehículo de la base de datos
            EntidadVehiculo v = ov.obtenerVehiculo(vehiDTO);

            // Se crea un objeto PlacaDTO con el número de serie de la placa y el vehículo obtenido
            CrearPlaca cp = new CrearPlaca();
            PlacaDTO placaDTO = new PlacaDTO(txtSeriePlaca.getText(), v);

            // Se crea la placa en la base de datos
            cp.crearPlaca(placaDTO, p);

            // Se muestra un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Placa generada con éxito.", "¡Éxito!", JOptionPane.INFORMATION_MESSAGE);

            // Se abre el formulario de trámites
            frmTramites formTramites = new frmTramites();
            formTramites.setVisible(true);
        } catch (Exception ex) {
            // Se muestra un mensaje de error si ocurre una excepción durante el proceso
            Logger.getLogger(frmGenerarPlacas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnContinuarAutoNuevoActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        String rfc = txtRFCAuto.getText();
        comboBoxVehiculos.removeAllItems();
        try {
            ObtenerPersona obtener = new ObtenerPersona();
            PersonaDTO p = obtener.obtenerPersona(rfc);
            EntidadPersona p_aux = new EntidadPersona(p.getId(),p.getRfc(),p.getNombres(),p.getApellidoP(),p.getApellidoM(), p.getFechaNacimiento(), p.getTel(),p.isDiscapacidad(),p.getInfo(),p.getInfoTramite());
            this.p = p_aux;

            // Obtener la licencia de la persona
            ObtenerLicencia obtenerL = new ObtenerLicencia();
            LicenciaDTO l = obtenerL.obtenerPorPersona(p.getId());
            Date hoy = new Date();
            if(l != null){
                if(l.getFechaVencimiento().compareTo(hoy)>0){
                    ObtenerVehiculo ov = new ObtenerVehiculo();
                    List<EntidadVehiculo> vehiculos = ov.obtenerListaPorPersona(p);
                    habilitarCampos();
                    JOptionPane.showMessageDialog(this, "El usuario tiene una licencia valida y vehiculos para generarles una placa", "¡Correcto!", JOptionPane.INFORMATION_MESSAGE);
                    for (EntidadVehiculo vehiculo : vehiculos) {
                            comboBoxVehiculos.addItem(vehiculo.getSerie() + " "+ vehiculo.getMarca() + " "+ vehiculo.getModelo());
                    }
                }else{
                    JOptionPane.showMessageDialog(this,"El usuario no tiene una licencia valida", "¡Error!", JOptionPane.ERROR_MESSAGE);

                }
            }else{
                JOptionPane.showMessageDialog(this,"El usuario no cuenta con ninguna licencia", "¡Correcto!", JOptionPane.ERROR_MESSAGE);

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void txtSeriePlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeriePlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeriePlacaActionPerformed

    private void comboBoxVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxVehiculosActionPerformed

    private void btnAtrasGenerarPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasGenerarPlacasActionPerformed
        // TODO add your handling code here:
        frmPlacas formPlacas = new frmPlacas();
        formPlacas.setVisible(true);
    }//GEN-LAST:event_btnAtrasGenerarPlacasActionPerformed
    
    private void habilitarCampos(){
    txtSeriePlaca.setEditable(true);
    comboBoxVehiculos.setEnabled(true);
    }
    
    private VehiculoDTO convertirDTO(EntidadVehiculo v){
        return new VehiculoDTO(v.getSerie(),
                               v.getPersona());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGenerarPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGenerarPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGenerarPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGenerarPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGenerarPlacas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasGenerarPlacas;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnContinuarAutoNuevo;
    private javax.swing.JComboBox<String> comboBoxVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtRFCAuto;
    private javax.swing.JTextField txtSeriePlaca;
    // End of variables declaration//GEN-END:variables
}
