/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author franc
 */
public class frmPlacas extends javax.swing.JFrame {

    /**
     * Creates new form frmPlacas
     */
    public frmPlacas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAutoNuevo = new javax.swing.JButton();
        btnAñadirPlaca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAtrasPlacas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAutoNuevo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAutoNuevo.setForeground(new java.awt.Color(0, 51, 102));
        btnAutoNuevo.setText("Registrar vehiculo");
        btnAutoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAutoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 710, 60));

        btnAñadirPlaca.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAñadirPlaca.setForeground(new java.awt.Color(0, 51, 102));
        btnAñadirPlaca.setText("Añadir placa");
        btnAñadirPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadirPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, 710, 70));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autoNuevo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 18, -1, 152));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autoUsado.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 188, -1, 169));

        btnAtrasPlacas.setBackground(new java.awt.Color(0, 51, 102));
        btnAtrasPlacas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAtrasPlacas.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasPlacas.setText("Atras");
        btnAtrasPlacas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAtrasPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasPlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtrasPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, 211, 55));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoNuevoActionPerformed
        // TODO add your handling code here:
        frmVehiculoNuevo formAutoNuevo = new frmVehiculoNuevo();
        formAutoNuevo.setVisible(true);
    }//GEN-LAST:event_btnAutoNuevoActionPerformed

    private void btnAñadirPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPlacaActionPerformed
        frmGenerarPlacas frmGenerarPlacas = new frmGenerarPlacas();
        frmGenerarPlacas.setVisible(true);
    }//GEN-LAST:event_btnAñadirPlacaActionPerformed

    private void btnAtrasPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasPlacasActionPerformed
        // TODO add your handling code here:
        frmTramites formGenerarPlacas = new frmTramites();
        formGenerarPlacas.setVisible(true);
    }//GEN-LAST:event_btnAtrasPlacasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPlacas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasPlacas;
    private javax.swing.JButton btnAutoNuevo;
    private javax.swing.JButton btnAñadirPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
