/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import Negocio.crearLicencia;
import java.awt.Color;

/**
 *
 * @author franc
 */
public class frmTramites extends javax.swing.JFrame {

    /**
     * Creates new form frmTramites
     */
    public frmTramites() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTramitesAtras = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        btnLicencias = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramitesAtras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnTramitesAtras.setForeground(new java.awt.Color(0, 102, 102));
        btnTramitesAtras.setText("Atras");
        btnTramitesAtras.setBorder(null);
        btnTramitesAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTramitesAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 90));

        btnPlacas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPlacas.setForeground(new java.awt.Color(0, 102, 102));
        btnPlacas.setText("PLACAS");
        btnPlacas.setBorder(null);
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 260, 340, 55));

        btnLicencias.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLicencias.setForeground(new java.awt.Color(0, 102, 102));
        btnLicencias.setText("LICENCIAS");
        btnLicencias.setBorder(null);
        btnLicencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLicenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLicenciasMouseExited(evt);
            }
        });
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });
        jPanel1.add(btnLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/licencia.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nissan-altima-2866605_1280 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 20, 340, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        // TODO add your handling code here:
        frmLicencias formLicencia = new frmLicencias();
        formLicencia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLicenciasActionPerformed

    private void btnTramitesAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesAtrasActionPerformed
        // TODO add your handling code here:
        frmMenu btnBack = new frmMenu();
        btnBack.setVisible(true);
    }//GEN-LAST:event_btnTramitesAtrasActionPerformed

    private void btnLicenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLicenciasMouseEntered
        // TODO add your handling code here:
        btnLicencias.setBackground(new Color(204,255,255));
    }//GEN-LAST:event_btnLicenciasMouseEntered

    private void btnLicenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLicenciasMouseExited
        // TODO add your handling code here:
        btnLicencias.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnLicenciasMouseExited

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        // TODO add your handling code here:
        frmPlacas formPlaca = new frmPlacas();
        formPlaca.setVisible(true);
    }//GEN-LAST:event_btnPlacasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTramites().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnTramitesAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
