/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import DTO.LicenciaDTO;
import DTO.PersonaDTO;
import DTO.PlacaDTO;
import DTO.TramiteDTO;
import DTO.VehiculoDTO;
import EntidadesJPA.EntidadPersona;
import EntidadesJPA.EntidadTramite;
import EntidadesJPA.EntidadVehiculo;
import Negocio.CrearPlaca;
import Negocio.CrearTramite;
import Negocio.CrearVehiculo;
import Negocio.ObtenerLicencia;
import Negocio.ObtenerPersona;
import Negocio.ObtenerPlaca;
import Negocio.ObtenerVehiculo;
import Negocio.crearLicencia;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class frmVehiculoNuevo extends javax.swing.JFrame {
EntidadPersona p;
    /**
     * Creates new form frmAutoNuevo
     */
    public frmVehiculoNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtRFCAuto = new javax.swing.JTextField();
        btnContinuarAutoNuevo = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JLabel();
        txtNoDeSerie = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnAtrasVehiculo = new javax.swing.JButton();
        comboBoxTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(0, 51, 102));

        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("LICENCIA VIGENTE");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("RFC");

        btnContinuarAutoNuevo.setBackground(new java.awt.Color(0, 102, 102));
        btnContinuarAutoNuevo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnContinuarAutoNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuarAutoNuevo.setText("Continuar");
        btnContinuarAutoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarAutoNuevoActionPerformed(evt);
            }
        });

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRFCAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnContinuarAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRFCAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(btnContinuarAutoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 300, 430));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR AUTO NUEVO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 310, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. de serie");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 370, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Linea");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        txtTipo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setText("Tipo");
        jPanel1.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txtNoDeSerie.setEditable(false);
        txtNoDeSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoDeSerieActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoDeSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, -1));

        txtMarca.setEditable(false);
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, -1));

        txtLinea.setEditable(false);
        jPanel1.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        txtColor.setEditable(false);
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, -1));

        txtModelo.setEditable(false);
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, -1));

        btnAtrasVehiculo.setBackground(new java.awt.Color(0, 102, 102));
        btnAtrasVehiculo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAtrasVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnAtrasVehiculo.setText("Atras");
        btnAtrasVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtrasVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 190, 50));

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camion", "Moto" }));
        comboBoxTipo.setEnabled(false);
        jPanel1.add(comboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoDeSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoDeSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoDeSerieActionPerformed

    private void btnContinuarAutoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarAutoNuevoActionPerformed
        try{
            // Se crea un objeto VehiculoDTO con el número de serie y la información de la persona
            VehiculoDTO vehiculo = new VehiculoDTO(txtNoDeSerie.getText(), this.p);

            // Se intenta obtener el vehículo de la base de datos
            ObtenerVehiculo ov = new ObtenerVehiculo();
            EntidadVehiculo v = ov.obtenerVehiculo(vehiculo);

            // Si el vehículo no existe en la base de datos, se crea
            if (v == null) {
                // Se crea un objeto VehiculoDTO completo
                VehiculoDTO v_completo = crearVehiculoDTO();

                // Se crea el vehículo en la base de datos
                CrearVehiculo cv = new CrearVehiculo();
                cv.crearVehiculo(v_completo);

                // Se muestra un mensaje de éxito
                JOptionPane.showMessageDialog(this, "Vehículo agregado.", "¡Éxito!", JOptionPane.INFORMATION_MESSAGE);

                // Se abre el formulario de trámites
                frmTramites formTramites = new frmTramites();
                formTramites.setVisible(true);
            } else {
                // Si el vehículo ya existe, se muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "El vehículo ya existe. Por favor, regrese al menú anterior para generar una placa.", "¡Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            // Se muestra un mensaje de error si ocurre una excepción durante el proceso
            JOptionPane.showMessageDialog(this, ex.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContinuarAutoNuevoActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        // Se obtiene el RFC del campo de texto
         String rfc = txtRFCAuto.getText();

         try {
             // Se obtiene la información de la persona con el RFC proporcionado
             ObtenerPersona obtener = new ObtenerPersona();
             PersonaDTO p = obtener.obtenerPersona(rfc);

             // Se crea un objeto EntidadPersona con la información obtenida de PersonaDTO
             EntidadPersona p_aux = new EntidadPersona(p.getId(), p.getRfc(), p.getNombres(), p.getApellidoP(), p.getApellidoM(), p.getFechaNacimiento(), p.getTel(), p.isDiscapacidad(), p.getInfo(), p.getInfoTramite());
             this.p = p_aux;

             // Se obtiene la licencia de la persona
             ObtenerLicencia obtenerL = new ObtenerLicencia();
             LicenciaDTO l = obtenerL.obtenerPorPersona(p.getId());

             // Se obtiene la fecha actual
             Date hoy = new Date();

             // Se verifica si la persona tiene una licencia válida
             if (l != null) {
                 if (l.getFechaVencimiento().compareTo(hoy) > 0) {
                     // Si la licencia es válida, se muestra un mensaje y se habilitan los campos
                     JOptionPane.showMessageDialog(this, "El usuario tiene una licencia válida", "¡Correcto!", JOptionPane.INFORMATION_MESSAGE);
                     habilitarCampos();
                 } else {
                     // Si la licencia no es válida, se muestra un mensaje de error
                     JOptionPane.showMessageDialog(this, "El usuario no tiene una licencia válida", "¡Error!", JOptionPane.ERROR_MESSAGE);
                 }
             } else {
                 // Si la persona no tiene ninguna licencia, se muestra un mensaje
                 JOptionPane.showMessageDialog(this, "El usuario no cuenta con ninguna licencia", "¡Correcto!", JOptionPane.ERROR_MESSAGE);
             }
         } catch (Exception ex) {
             // Se muestra un mensaje de error si ocurre una excepción durante el proceso
             JOptionPane.showMessageDialog(this, ex.getMessage(), "¡Error!", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnAtrasVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasVehiculoActionPerformed
        // TODO add your handling code here:
        frmPlacas formPlacas = new frmPlacas();
        formPlacas.setVisible(true);
    }//GEN-LAST:event_btnAtrasVehiculoActionPerformed
    private void habilitarCampos(){
    txtNoDeSerie.setEditable(true);
    txtMarca.setEditable(true);
    txtLinea.setEditable(true);
    txtColor.setEditable(true);
    txtModelo.setEditable(true);
    comboBoxTipo.setEnabled(true);
    }
    //    public VehiculoDTO(String serie, String color, String marca, String modelo, String tipo, boolean nuevo, EntidadPersona persona) {

    private VehiculoDTO crearVehiculoDTO(){
        int select = comboBoxTipo.getSelectedIndex();
        VehiculoDTO v = new VehiculoDTO(txtNoDeSerie.getText(), txtColor.getText(), txtMarca.getText(), txtModelo.getText(), comboBoxTipo.getItemAt(select), true, this.p);
        return v;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVehiculoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVehiculoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVehiculoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVehiculoNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVehiculoNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasVehiculo;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnContinuarAutoNuevo;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNoDeSerie;
    private javax.swing.JTextField txtRFCAuto;
    private javax.swing.JLabel txtTipo;
    // End of variables declaration//GEN-END:variables
}
